In [11]:
%run ./student_health_eda.ipynb

X.head()

Path to competition files: /Users/jaquesgillis/.cache/kagglehub/competitions/playground-series-s6e7
length of table: 690088
0.1101294327679948 proportion null rows for sleep_duration
0.011350726284184046 proportion null rows for heart_rate
0.020139460474606137 proportion null rows for bmi
0.07658878287986459 proportion null rows for calorie_expenditure
0.020165544104520004 proportion null rows for step_count
0.010000173890866092 proportion null rows for exercise_duration
0.06300210987584193 proportion null rows for water_intake
0.010000173890866092 proportion null rows for diet_type
0.12000063759984234 proportion null rows for stress_level
0.0845269009169845 proportion null rows for sleep_quality
0.05306714505976049 proportion null rows for physical_activity_level
0.04141790612211776 proportion null rows for smoking_alcohol
0.030971412341614404 proportion null rows for gender
Baseline balanced accuracy score: 0.8393219639478678

,sleep_duration,heart_rate,bmi,calorie_expenditure,step_count,exercise_duration,water_intake,veg,non-veg,balanced,yes,occasional,no,female,other,male,sleep_quality_encoded,stress_level_encoded,physical_activity_level_encoded
0,5.22,70.6,25.66,2174.0,1326.0,19.8,1.86,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,2.0,0.0
1,5.53,71.3,25.84,1966.0,9891.0,49.9,1.26,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0
2,5.29,75.4,24.54,2688.0,14216.0,38.1,1.60,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,2.0,2.0
3,4.70,77.2,23.13,2630.0,7174.0,59.9,2.02,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,2.0,2.0
4,7.23,73.4,28.44,2560.0,6584.0,46.0,2.25,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0

In [13]:
X.head()

,sleep_duration,heart_rate,bmi,calorie_expenditure,step_count,exercise_duration,water_intake,veg,non-veg,balanced,yes,occasional,no,female,other,male,sleep_quality_encoded,stress_level_encoded,physical_activity_level_encoded
0,5.22,70.6,25.66,2174.0,1326.0,19.8,1.86,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,2.0,0.0
1,5.53,71.3,25.84,1966.0,9891.0,49.9,1.26,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0
2,5.29,75.4,24.54,2688.0,14216.0,38.1,1.60,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,2.0,2.0
3,4.70,77.2,23.13,2630.0,7174.0,59.9,2.02,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,2.0,2.0
4,7.23,73.4,28.44,2560.0,6584.0,46.0,2.25,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0